#input("I can hardly wait to go to school today because I have something special to show my friends! It's my new (noun) that I've been (verb ending in-ing) for (number) (time unit). I know they're going to be so (emotion) when they see it.")

verb1=input("enter a VERB: ")
name1=input("enter a NAME: ")
color1=input("enter a color:")
food1=input("enter a food:")
subject1=input("enter a subject:")
Animal1=input("enter a Animal:")
Number1=input("enter a Number:")
sport1=input("enter a Sport:")
superhero1=input("enter a Superhero:")
Movie1=input("enter a movie:")
adjective1=input("enter a adjective:")
Noun1=input("enter a noun:")
print("I",verb1, "today.")
print("I saw",name1,"today too!")
print("I heard", color1, " is his favorite color. ")
print("I heard", food1, " is his favorite food. " )
print("I liked that" , subject1, " is his favorite subject.")
print("I was surprised that" , Animal1, " is his favorite animal.")
print("I am very interested that" , Number1, " is his favorite number.")
print("I'm surprised that" , sport1, " is his favorite sport.")
print("I would like to chill with him since" , superhero1, " is his favorite superhero." )
print("I heard that" , Movie1, " is his all-time favorite movie.")
print("Today was a very" , adjective1, "day in the park.")
print("I went to the" , Noun1, " today.")