#input("I can hardly wait to go to school today because I have something special to show my friends! It's my new (noun) that I've been (verb ending in-ing) for (number) (time unit). I know they're going to be so (emotion) when they see it.")

verb1=input("enter a VERB: ")
name1=input("enter a NAME: ")
color1=input("enter a color:")
food1=input("enter a food:")
subject1=input("enter a subject:")
Animal1=input("enter a Animal:")
Number1=input("enter a Number:")
sport1=input("enter a Sport:")
superhero1=input("enter a Superhero:")
Movie1=input("enter a movie:")
adjective1=input("enter a adjective:")
Noun1=input("enter a noun:")
adjective2=input("enter a adjective:")
verb2=input("enter a VERB:")
verb3=input("enter a VERB:")
Noun2=input("enter a noun:")
Animal2=input("enter a Animal:")
Superhero2=input("enter a Superhero:")
Movie2=input("enter a movie:")
food2=input("enter a food:")
print("I",verb1, "today.")
print("I saw",name1,"today too!")
print("I heard", color1, " is his favorite color. ")
print("I heard", food1, " is his favorite food. " )
print("I liked that" , subject1, " is his favorite subject.")
print("I was surprised that" , Animal1, " is his favorite animal.")
print("I am very interested that" , Number1, " is his favorite number.")
print("I'm surprised that" , sport1, " is his favorite sport.")
print("I would like to chill with him since" , superhero1, " is his favorite superhero." )
print("I heard that" , Movie1, " is his all-time favorite movie.")
print("Today was a very" , adjective1, "day in the park.")
print("I went to the" , Noun1, " today.")
print("Yesterday, a" , adjective2, "spaceship landed in my backyard. Out stepped a green alien holding a toaster.")
print("The alien looked around and" , verb2, "loudly on the grass. Suddenly, it pulled a tiny lever.")
print("When I was walked around, I accidentally", verb3, "on the alien.")
print("One spooky night, I walked up to the old", Noun2, " house on the hill.")
print("Once I got into the house, I saw a scary", Animal2, " on the hill.")
print("I ran for my life, but suddenly", Superhero2, " came to save me." )
print("After that, we watched a movie called", Movie2, "together.")
print("During the movie, we had to get some", food2, "while sitting on the couch.")