x1=int(input("Enter first number"))
x2=int(input("Enter second number"))
print(f"{x1} + {x2} = ",(x1+x2))
print(f"{x1} - {x2} = ",(x1-x2))
print(f"{x1} * {x2} = ",(x1*x2))
print(f"{x1} / {x2} = ",(x1/x2))